Loterie/Controllers/ResultsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LoterieCDA.Controllers
{
    public class ResultsController : Controller
    {
        // GET: ResultsController
        public ActionResult Results()
        {
            return View();
        }

        // GET: ResultsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ResultsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ResultsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ResultsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ResultsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ResultsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ResultsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Loterie/Controllers/RulesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LoterieCDA.Controllers
{
    public class RulesController : Controller
    {
        // GET: RulesController
        public ActionResult Rules()
        {
            return View();
        }

        // GET: RulesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RulesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RulesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RulesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RulesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RulesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RulesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Loterie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LoterieCDA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LoterieCDA.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="header-wrapper">
            <div class="header-infos">
                <div class="header-title"> PROCHAIN TIRAGE </div>
                @*@{
                    int index = 1;
                }
                @foreach (var item in Model)
                {
                    if (index == Model.Count())
                    {
                        <input type="hidden" id="dateNextSessions" name="dateNextSessions" value="@Html.DisplayFor(modelItem => item.Date)" />
                    }
                    index++;

                }*@
                <div class="header-timer" id="timerScreen"></div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="footer-menu">
            <div class="footer-button-wrapper">
                <a asp-controller="Home" asp-action="Index">
                    <div class="footer-button-cercleExt">
                        <div class="footer-button-img"></div>
                    </div>
                </a>
                <div class="footer-button-name"> ACCUEIL </div>
            </div>
            <div class="footer-button-wrapper">
                <a asp-controller="Results" asp-action="Results">
                    <div class="footer-button-cercleExt">
                        <div class="footer-button-img"></div>
                    </div>
                </a>
                <div class="footer-button-name"> RESULTAT </div>
            </div>
            <div class="footer-button-wrapper">
                <a asp-controller="Rules" asp-action="Rules">
                    <div class="footer-button-cercleExt">
                        <div class="footer-button-img"></div>
                    </div>
                </a>
                <div class="footer-button-name"> REGLES </div>
            </div>
        </div>
    </footer>    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>